BlogTemplate/mysite_env1/mysite1/blog1/urls.py
from django.urls import path
from . import views

urlpatterns = [
	#博客首页
	path('',views.blog_list, name="blog_list"),
    path('<int:blog_pk>',views.blog_detail, name="blog_detail"),
    path('type/<int:type_pk>',views.blogs_with_type, name="blogs_with_type"),
    path('date/<int:year>/<int:month>', views.blog_dates, name="blog_dates"),
]

BlogTemplate/mysite_env1/mysite1/mysite1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from weather.views import DelWeather



urlpatterns = [
    path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('blog/',include('blog1.urls')),
    path('picture/',views.blog_picture,name="picture"),
    path('login/',views.login,name="login"),
    path('registered/',views.registered, name="registered"),
    path('comment/',include('comment.urls')),
    path('weather/',include('weather.urls')),
    path('del',DelWeather,name="del"),
]
urlpatterns += static(settings.MEDIA_URL, coument_root=settings.MEDIA_ROOT)

BlogTemplate/mysite_env1/mysite1/mysite1/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(min_length=3, max_length=20)
    password = forms.CharField(min_length=6)

class RegisteredForm(forms.Form):
    username = forms.CharField(min_length=3, max_length=20)
    email = forms.EmailField()
    password = forms.CharField(min_length=6)
    password_again = forms.CharField(min_length=6)

BlogTemplate/mysite_env1/mysite1/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
<!--     <link rel="stylesheet" type="text/css" href="/static/base.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
    {% block head_extends %}{% endblock %}
</head>
<body>
	<div class="navbar navbar-default" role="navigation">
		<div class="container-fluid"><!-- 按照百分比填满页面 -->
			<div class="navbar-header"><!-- logo -->
				<button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'home' %}">个人博客网站</a>
			</div>
			<div class="collapse navbar-collapse" id="navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="{% block nav_home_active %}{% endblock %}">
						<a href="{% url 'home' %}">首页</a>
					</li>
					<li class="{% block nav_blog_active %}{% endblock %}">
						<a href="{% url 'blog_list' %}">博客</a>
					</li>
                    <li class="{% block nav_weather_active %}{% endblock %}">
						<a href="{% url 'weather' %}">天气</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
    {% block content %}{% endblock %}
</body>
</html>

BlogTemplate/mysite_env1/mysite1/templates/error.html
{% extends 'base.html' %}

{% block title %}我的网站|错误{% endblock %}


{% block nav_home_active %}active{% endblock %}

{% block content %}
    {{ message }}，<a href="{{ referer }}">返回</a>
{% endblock %}

BlogTemplate/mysite_env1/mysite1/templates/home.html
{% extends 'base.html' %}

{% load staticfiles %}{# 必须加载静态文件 #}

{% block title %}我的网站|首页{% endblock %}

{% block head_extends %}
	<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
    <script src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}

	<h3 class="home_content">欢迎访问我的网站，随便看</h3>
    <!-- 图表容器 DOM -->
    <div id="container"></div>

    {# 热门博客数量#}
    <div class="hot-date" style="">
        <h3>今天热门点击</h3>
    <ul>
        {% for today in today_read %}
             <li><a href="{% url 'blog_detail' today.content_object.pk %}">{{ today.content_object.title }}</a>（{{ today.read_num }}）</li>
         {% empty %}
            <p>暂无热门阅读</p>
        {% endfor %}
    </ul>

    <h3>昨天热门点击</h3>
    <ul>
        {% for yesterday in yesterday_read %}
            <li><a href="{% url 'blog_detail' yesterday.id %}">{{ yesterday.title}}</a>（{{ yesterday.yesterday_read_sum }}）</li>
         {% empty %}
            <p>暂无热门阅读</p>
        {% endfor %}
    </ul>
        <h3>7天热门点击</h3>
        <ul>
            {% for week in week_read %}
                <li><a href="{% url 'blog_detail' week.id %}">{{ week.title}}</a>（{{ week.week_read_sum }}）</li>
             {% empty %}
                <p>暂无热门阅读</p>
            {% endfor %}
        </ul>
 </div>

     <script>
        // 图表配置
        var options = {
            chart: {
                type: 'line'                          //指定图表的类型，默认是折线图（line）
            },
            title: {
                text: null                 // 标题
            },
            xAxis: {
                categories: {{ dates|safe }},  // x 轴分类
                tickmarkPlacement: 'on',//让月份的值对应到Y轴线上
                title: { //标题
                    text: '前七天的阅读变化'
                }
            },
            yAxis: {
                title: {
                    text: null                // y 轴标题
                },
                labels:{enabled:false}, //去掉y轴值
                gridLineDashStyle:'Dash'//y轴线为虚线
            },
            series: [{                              // 数据列
                name: '阅读数',                        // 数据列名
                data: {{ read_nums }}                 // 数据
            }],
            //在数据点上显示一些数据信息标签
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                        }
                    }
                },
            //去掉图例
            legend:{enabled:false},
            //去掉版权信息
            credits:{enabled:false}
        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);
    </script>
{% endblock %}

BlogTemplate/mysite_env1/mysite1/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}登录{% endblock %}

{% block head_extends %}
    <link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">
{% endblock %}

{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">登录</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <label for="id_username">账号</label>
                            <input type="text" name="username" required placeholder="账号" id="id_username" class="form-control">
                            <label for="id_password">密码</label>
                            <input type="password" name="password" required placeholder="密码" id="id_password" class="form-control">
                            <input class="btn btn-primary pull-right" type="submit" value="登录">
                        </form>
                        <p class="pull-left text-danger errors">
                            {# 自带的验证 #}
                            {% for k,v in  login_form.errors.items %}
                                    <span style="list-style: none">{{ v }}</span>
                            {% endfor %}
                        <span style="color: #f40;">{{ error }}</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

BlogTemplate/mysite_env1/mysite1/templates/registered.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}登录{% endblock %}

{% block head_extends %}
    <link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">
{% endblock %}

{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">登录</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <label for="id_username">账号</label>
                            <input type="text" name="username" required placeholder="账号" id="id_username" class="form-control">
                            <label for="id_email">邮箱</label>
                            <input type="email" name="email" required placeholder="邮箱" id="id_email" class="form-control">
                            <label for="id_password">密码</label>
                            <input type="password" name="password" required placeholder="密码" id="id_password" class="form-control">
                            <label for="id_password_again">确认密码</label>
                            <input type="password" name="password_again" required placeholder="确认密码" id="password_again" class="form-control">
                            <input class="btn btn-primary pull-right" type="submit" value="登录">
                             <p class="pull-left text-danger errors">
                            {# 自带的验证 #}
                             {% for k,v in registered_form.errors.items %}
                                 {{ v }}
                             {% endfor %}
                            {{ errors }}
                        </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}